name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: npm run deploy
      